[project]
name = "pytest-mock-resources"
version = "2.13.0"
description = "A pytest plugin for easily instantiating reproducible mock resources."
authors = [
    { name = "Omar Khan", email = "oakhan3@gmail.com" },
    { name = "Dan Cardin", email = "ddcardin@gmail.com" },
    { name = "Gabriel Michael", email = "gabriel.j.michael@gmail.com" },
    { name = "Prateek Pisat", email = "pisatprateek12@gmail.com" },
]
license = { text = "MIT" }
keywords = ["pytest", "sqlalchemy", "docker", "fixture", "mock"]
classifiers = ["Framework :: Pytest"]
readme = "README.md"
requires-python = ">=3.8,<4"
dependencies = [
    "pytest>=1.0",
    "sqlalchemy>1.0,!=1.4.0,!=1.4.1,!=1.4.2,!=1.4.3,!=1.4.4,!=1.4.5,!=1.4.6,!=1.4.7,!=1.4.8,!=1.4.9,!=1.4.10,!=1.4.11,!=1.4.12,!=1.4.13,!=1.4.14,!=1.4.15,!=1.4.16,!=1.4.17,!=1.4.18,!=1.4.19,!=1.4.20,!=1.4.21,!=1.4.22,!=1.4.23",
    "typing_extensions",
    "importlib-metadata; python_version < '3.8'",
]

[project.optional-dependencies]
docker = ["python-on-whales>=0.22.0", "filelock"]
postgres = ["psycopg2", "python-on-whales>=0.22.0", "filelock"]
postgres-binary = ["psycopg2-binary", "python-on-whales>=0.22.0", "filelock"]
postgres-async = ["asyncpg", "python-on-whales>=0.22.0", "filelock"]
redshift = ["boto3", "moto", "sqlparse", "python-on-whales>=0.22.0", "filelock"]
mongo = ["pymongo", "python-on-whales>=0.22.0", "filelock"]
moto = ["boto3", "python-on-whales>=0.22.0", "filelock"]
redis = ["redis", "python-on-whales>=0.22.0", "filelock"]
mysql = ["pymysql>=1.0", "python-on-whales>=0.22.0", "filelock"]

[project.urls]
Repository = "https://github.com/schireson/pytest-mock-resources"

[project.scripts]
pmr = "pytest_mock_resources.cli:main"

[project.entry-points."pytest11"]
pytest_mock_resources = "pytest_mock_resources"

[dependency-groups]
dev = [
    "botocore==1.33.13",
    "coverage<7.3",
    "moto>=2.3.2,<5",
    "pymongo<4.8",
    "pytest<8",
    "redis<6",
    "mypy>=1.0",
    "pytest-asyncio",
    "pytest-xdist",
    "responses>=0.23.0",
    "ruff==0.1.15",
    "types-PyMySQL>=1.0.2,<2",
    "types-dataclasses>=0.6.5,<0.7",
    "types-filelock>=3.2.7,<4",
    "types-redis>=3.5.6,<4",
    "types-requests",
    "types-six>=1.16.0,<2",
]
docs = [
    "sphinx==3.3.0",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
    "sphinx-autobuild",
    "docutils<0.18",
    "myst-parser",
    "sphinx-pyproject",
]

[build-system]
requires = ["uv_build>=0.9.25"]
build-backend = "uv_build"

[tool.ruff]
src = ["src", "tests"]
line-length = 100

target-version = "py37"
select = ["C", "D", "E", "F", "I", "N", "Q", "RET", "RUF", "S", "T", "UP", "YTT"]
ignore = [
    "D1",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
    "C901",
    "E501",
    "S101",
]

[tool.ruff.isort]
known-first-party = ["pytest_mock_resources", "tests"]
order-by-type = false

[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["D", "S", "RUF012", "N801"]


[tool.mypy]
strict_optional = true
ignore_missing_imports = true
warn_unused_ignores = true
incremental = true
plugins = 'sqlalchemy.ext.mypy.plugin'
exclude = 'tests/examples'

[tool.pytest.ini_options]
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ELLIPSIS"
addopts = "--doctest-modules -vv --ff --strict-markers"
norecursedirs = ".* build dist *.egg tests/examples"
pytester_example_dir = "tests/examples"
pmr_multiprocess_safe = true
markers = ["postgres", "redshift", "mongo", "redis", "mysql"]
filterwarnings = [
    "error",
    "ignore:There is no current event loop:DeprecationWarning",
    "ignore:stream argument is deprecated. Use stream parameter in request directly:DeprecationWarning",
    "ignore:Boto3 will no longer support Python 3.7.*::boto3",
    "ignore:datetime.datetime.utcnow.*:DeprecationWarning",
    "ignore:'asyncio\\..*' is deprecated.*:DeprecationWarning",
    "ignore:Module globals.*:DeprecationWarning",
]

[tool.coverage.run]
source = ["src"]
branch = true
parallel = true

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = ["pragma: no cover"]
